"""
CryptoForge — Algorithm Registry
Defines the metadata and configuration for all supported cryptographic algorithms.
"""
from app.crypto.engines import (
    aes_encrypt,
    rsa_generate_keypair,
    sha256_hash,
    caesar_encrypt,
    blowfish_encrypt,
    chacha20_encrypt,
    hmac_sha256,
    base64_encode,
    rot13,
    vigenere,
    polybius,
    des_encrypt,
    multiplicative,
    affine,
    autokey,
    playfair,
    railfence,
    columnar,
    double_transposition,
    gcd,
    eea,
    ecc,
    diffie_hellman,
    digital_signature,
    generic_hash,
    md5,
    sha1,
    sha3,
)

ALGORITHMS = {
    # ── Already implemented ──
    "aes-256": {
        "id": "aes-256",
        "name": "AES-256",
        "category": "Symmetric",
        "difficulty": 4,
        "complexity": "O(1) per block",
        "description": "Advanced Encryption Standard with 256-bit key — the gold standard for symmetric encryption.",
        "parameters": ["key_size", "mode", "output_format"],
        "encrypt_fn": aes_encrypt,
    },
    "rsa-2048": {
        "id": "rsa-2048",
        "name": "RSA-2048",
        "category": "Asymmetric",
        "difficulty": 5,
        "complexity": "O(n³)",
        "description": "Rivest-Shamir-Adleman public-key cryptosystem for secure key exchange and digital signatures.",
        "parameters": ["bits"],
        "encrypt_fn": rsa_generate_keypair,
    },
    "sha-256": {
        "id": "sha-256",
        "name": "SHA-256",
        "category": "Hash Functions",
        "difficulty": 3,
        "complexity": "O(n)",
        "description": "Secure Hash Algorithm producing a 256-bit digest.",
        "parameters": ["output_format"],
        "encrypt_fn": sha256_hash,
    },
    "caesar": {
        "id": "caesar",
        "name": "Caesar Cipher",
        "category": "Classical Ciphers",
        "difficulty": 1,
        "complexity": "O(n)",
        "description": "The ancient substitution cipher that shifts each letter by a fixed number of positions.",
        "parameters": ["shift"],
        "encrypt_fn": caesar_encrypt,
    },
    "blowfish": {
        "id": "blowfish",
        "name": "Blowfish",
        "category": "Symmetric",
        "difficulty": 3,
        "complexity": "O(1)",
        "description": "A fast, compact symmetric block cipher with variable-length key up to 448 bits.",
        "parameters": ["output_format"],
        "encrypt_fn": blowfish_encrypt,
    },
    "chacha20": {
        "id": "chacha20",
        "name": "ChaCha20",
        "category": "Symmetric",
        "difficulty": 3,
        "complexity": "O(n)",
        "description": "A modern stream cipher designed for high performance.",
        "parameters": ["output_format"],
        "encrypt_fn": chacha20_encrypt,
    },
    "hmac-sha256": {
        "id": "hmac-sha256",
        "name": "HMAC-SHA256",
        "category": "Hash Functions",
        "difficulty": 2,
        "complexity": "O(n)",
        "description": "Hash-based Message Authentication Code providing data integrity.",
        "parameters": ["key", "output_format"],
        "encrypt_fn": hmac_sha256,
    },
    "base64": {
        "id": "base64",
        "name": "Base64 Encode",
        "category": "Encoding",
        "difficulty": 1,
        "complexity": "O(n)",
        "description": "Base64 encoding/decoding.",
        "parameters": [],
        "encrypt_fn": base64_encode,
    },
    "rot13": {
        "id": "rot13",
        "name": "ROT13",
        "category": "Classical Ciphers",
        "difficulty": 1,
        "complexity": "O(n)",
        "description": "Simple letter substitution cipher replacing each letter with the 13th letter after it.",
        "parameters": [],
        "encrypt_fn": rot13,
    },

    # ── User to implement ──
    "vigenere": {
        "id": "vigenere",
        "name": "Vigenere Cipher",
        "category": "Classical Ciphers",
        "difficulty": 2,
        "complexity": "O(n)",
        "description": "A method of encrypting alphabetic text by using a series of interwoven Caesar ciphers based on the letters of a keyword.",
        "parameters": ["key"],
        "encrypt_fn": vigenere,
    },
    "polybius": {
        "id": "polybius",
        "name": "Polybius Square",
        "category": "Classical Ciphers",
        "difficulty": 2,
        "complexity": "O(n)",
        "description": "A device for fractionating plaintext characters so that they can be represented by a smaller set of symbols.",
        "parameters": [],
        "encrypt_fn": polybius,
    },
    "des": {
        "id": "des",
        "name": "DES",
        "category": "Symmetric",
        "difficulty": 3,
        "complexity": "O(1) per block",
        "description": "Data Encryption Standard - a legacy symmetric-key method of data encryption.",
        "parameters": ["key"],
        "encrypt_fn": des_encrypt,
    },
    "multiplicative": {
        "id": "multiplicative",
        "name": "Multiplicative Cipher",
        "category": "Classical Ciphers",
        "difficulty": 2,
        "complexity": "O(n)",
        "description": "A substitution cipher where the plaintext is multiplied by a key modulo the alphabet size.",
        "parameters": ["key"],
        "encrypt_fn": multiplicative,
    },
    "affine": {
        "id": "affine",
        "name": "Affine Cipher",
        "category": "Classical Ciphers",
        "difficulty": 2,
        "complexity": "O(n)",
        "description": "A monoalphabetic substitution cipher where each letter is mapped to its numeric equivalent, encrypted using a linear mathematical function, and converted back to a letter.",
        "parameters": ["a", "b"],
        "encrypt_fn": affine,
    },
    "autokey": {
        "id": "autokey",
        "name": "Autokey Cipher",
        "category": "Classical Ciphers",
        "difficulty": 2,
        "complexity": "O(n)",
        "description": "A cipher that incorporates the plaintext into the key to avoid the periodicity vulnerabilities of Vigenère.",
        "parameters": ["key"],
        "encrypt_fn": autokey,
    },
    "playfair": {
        "id": "playfair",
        "name": "Playfair Cipher",
        "category": "Classical Ciphers",
        "difficulty": 3,
        "complexity": "O(n)",
        "description": "A manual symmetric encryption technique that encrypts pairs of letters instead of single letters.",
        "parameters": ["key"],
        "encrypt_fn": playfair,
    },
    "railfence": {
        "id": "railfence",
        "name": "Rail Fence Cipher",
        "category": "Classical Ciphers",
        "difficulty": 2,
        "complexity": "O(n)",
        "description": "A form of transposition cipher that writes text downwards and diagonally on successive rails.",
        "parameters": ["key"],
        "encrypt_fn": railfence,
    },
    "columnar": {
        "id": "columnar",
        "name": "Columnar Transposition",
        "category": "Classical Ciphers",
        "difficulty": 3,
        "complexity": "O(n)",
        "description": "A transposition cipher that reads the plaintext across columns of a grid, then reads it out by column based on a keyword.",
        "parameters": ["key"],
        "encrypt_fn": columnar,
    },
    "double-transposition": {
        "id": "double-transposition",
        "name": "Double Transposition",
        "category": "Classical Ciphers",
        "difficulty": 3,
        "complexity": "O(n)",
        "description": "Applying columnar transposition twice using the same or different keywords to increase security.",
        "parameters": ["key1", "key2"],
        "encrypt_fn": double_transposition,
    },
    "gcd": {
        "id": "gcd",
        "name": "GCD (Greatest Common Divisor)",
        "category": "Math Functions",
        "difficulty": 1,
        "complexity": "O(log(min(a,b)))",
        "description": "Calculates the greatest common divisor of two integers using the Euclidean algorithm.",
        "parameters": ["a", "b"],
        "encrypt_fn": gcd,
    },
    "eea": {
        "id": "eea",
        "name": "Extended Euclidean Algorithm",
        "category": "Math Functions",
        "difficulty": 3,
        "complexity": "O(log(min(a,b)))",
        "description": "Finds the GCD of two integers and the coefficients of Bézout's identity.",
        "parameters": ["a", "b"],
        "encrypt_fn": eea,
    },
    "ecc": {
        "id": "ecc",
        "name": "Elliptic Curve Cryptography",
        "category": "Asymmetric",
        "difficulty": 5,
        "complexity": "O(log(n))",
        "description": "Public-key cryptography based on the algebraic structure of elliptic curves over finite fields.",
        "parameters": [],
        "encrypt_fn": ecc,
    },
    "diffie-hellman": {
        "id": "diffie-hellman",
        "name": "Diffie-Hellman Key Exchange",
        "category": "Asymmetric",
        "difficulty": 4,
        "complexity": "O(n³)",
        "description": "A method of securely exchanging cryptographic keys over a public channel.",
        "parameters": ["p", "g", "private_key"],
        "encrypt_fn": diffie_hellman,
    },
    "digital-signature": {
        "id": "digital-signature",
        "name": "Digital Signature",
        "category": "Asymmetric",
        "difficulty": 4,
        "complexity": "O(n³)",
        "description": "A mathematical scheme for verifying the authenticity of digital messages or documents.",
        "parameters": [],
        "encrypt_fn": digital_signature,
    },
    "hash-function": {
        "id": "hash-function",
        "name": "Generic Hash Function",
        "category": "Hash Functions",
        "difficulty": 2,
        "complexity": "O(n)",
        "description": "A generic hash function stub.",
        "parameters": [],
        "encrypt_fn": generic_hash,
    },
    "md5": {
        "id": "md5",
        "name": "MD5",
        "category": "Hash Functions",
        "difficulty": 3,
        "complexity": "O(n)",
        "description": "A widely used, but vulnerable, cryptographic hash function producing a 128-bit hash value.",
        "parameters": [],
        "encrypt_fn": md5,
    },
    "sha1": {
        "id": "sha1",
        "name": "SHA-1",
        "category": "Hash Functions",
        "difficulty": 3,
        "complexity": "O(n)",
        "description": "A cryptographic hash function which takes an input and produces a 160-bit hash value known as a message digest.",
        "parameters": [],
        "encrypt_fn": sha1,
    },
    "sha3": {
        "id": "sha3",
        "name": "SHA-3",
        "category": "Hash Functions",
        "difficulty": 4,
        "complexity": "O(n)",
        "description": "The latest member of the Secure Hash Algorithm family of standards, based on Keccak.",
        "parameters": [],
        "encrypt_fn": sha3,
    },
}
